# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-13 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='post_id',
            field=models.CharField(max_length=140),
        ),
    ]
